### ISSUE TITLE
Question: Does this library work on the newer Raspberry Pi 2?

### ISSUE THREAD

**Issue by emcpadden** [cymplecy/Scratch2GPIO#1]
Hello,

My 11 year old daughter and I were thinking about getting one of the new raspberry Pi2.  My daughter has been playing with Scratch for a couple of years and it seems like it would be fun to try to use Scratch to play in the real world by controlling things thru the GPIO.  

I just stumbled over your library and I was wondering if it works with the new Raspberry Pi2 boards that were recently released?

I must say, a project like this is so very valuable in working with kids to explore software, especially for creating projects that operate in the real world.  

Thanks for creating such a project!  If it works for the newer Pi2, I will try it out with my daughter ... I'm sure it will spark lots of creativity!

...Ed

**Comment by cymplecy** [comment]
Yes :) it works on all Pi models. :)
Simon

**Comment by emcpadden** [comment]
Perfect!  Thanks Simon.
